apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: js-app
  template:
    metadata:
      labels:
        app: js-app
    spec:
      containers:
      - name: js-app-container
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 3000
